utils::globalVariables(c("index", "time", "amplitude", "freq", "mean_amp", "train.dur",
                         "train.start", "train.end", "motif.id", "motif.dur", "amp",
                         "train.gap", "n.trains", "norm_amp_dB", "norm_amp_linear",
                         "high.f", "low.f", "sd", "var", "props.sd", "props.mean",
                         "props.ent", "props.cv", "dyn.exc", "dyn.exc.sd", "tem.exc",
                         "tem.exc.mean", "motif.start", "motif.end", "peak.id",
                         "peak.time", "peak.period", "specimen.id", "frequency",
                         "amp_cutoff", "train.id", "n.peaks", "train.period",
                         "peak.period.ms", "peak.amp", "peak.diff", "train.rate",
                         "pci", "temp_file"))
